COMP2084-Project-200465920/Controllers/BrowseController.cs
using COMP2084_Project_200465920.Data;
using COMP2084_Project_200465920.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace COMP2084_Project_200465920.Controllers
{
    public class BrowseController : Controller
    {
        //add DbContext to use the database
        private readonly ApplicationDbContext _context;

        public BrowseController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: /Browse
        public IActionResult Index()
        {

            // use genres DbSet to fetch list of categories to display to shoppers
            var genres = _context.Genres.OrderBy(c => c.Name).ToList();
            return View(genres);
        }

        // GET: /Browse/BrowseByGenre/1
        public IActionResult BrowseByGenre(int id)
        {
            // get media in selected genre
            var userId = GetUserId();
            var watchList = _context.WatchLists.Where(u => u.UserId == userId);
            var medias = _context.Medias.Where(m => m.GenreId == id)
                .OrderBy(m => m.Title).ToList();
            var genre = _context.Genres.Find(id);
            var tuple = new Tuple<IEnumerable<Media>, IEnumerable<WatchList>>(medias, watchList);
            ViewBag.Genre = genre.Name;
            return View(medias);
        }

        private string GetUserId()
        {
            // check session for an existing UserId for the user's cart
            if (HttpContext.Session.GetString("UserId") == null)
            {
                // this is user's 1st cart item
                var userId = "";
                if (User.Identity.IsAuthenticated)
                {
                    //user has logged in; use email
                    userId = User.Identity.Name;
                }

                // store userId in a session var
                HttpContext.Session.SetString("UserId", userId);
            }

            return HttpContext.Session.GetString("UserId");
        }
    }
}

COMP2084-Project-200465920/Controllers/MediasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using COMP2084_Project_200465920.Data;
using COMP2084_Project_200465920.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace COMP2084_Project_200465920.Controllers
{
    public class MediasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MediasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Medias
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Medias.Include(m => m.Genre);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Medias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var media = await _context.Medias
                .Include(m => m.Genre)
                .FirstOrDefaultAsync(m => m.MediaId == id);

            var reviews = _context.Reviews
                .Where(r => r.MediaId == id);
            if (media == null)
            {
                return NotFound();
            }

            var tuple = new Tuple<Media, IEnumerable<Review>>(media, reviews);

            return View(tuple);
        }

        // GET: Medias/Create
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "Name");
            return View("Create");
        }

        // POST: Medias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MediaId,Title,MediaType,Season,Episode,ReleaseDate,GenreId")] Media media, IFormFile Poster)
        {
            if (ModelState.IsValid)
            {
                if(Poster != null)
                {
                    var fileName = UploadPoster(Poster);
                    media.Poster = fileName;
                }
                _context.Add(media);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "Name", media.GenreId);
            return View("Create",media);
        }

        private string UploadPoster (IFormFile Photo)
        {
            //get temp location of uploaded photo
            var filePath = Path.GetTempFileName();

            var fileName = Guid.NewGuid() + "-" + Photo.FileName;

            //set destination path dynamically so it works on any system
            var uploadPath = System.IO.Directory.GetCurrentDirectory() + "\\wwwroot\\photos\\posters\\" + fileName;

            // actually execute the file copy now
            using (var stream = new FileStream(uploadPath, FileMode.Create))
            {
                Photo.CopyTo(stream);
            }

            return fileName;


        }

        // GET: Medias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("404");
            }

            var media = await _context.Medias.FindAsync(id);
            if (media == null)
            {
                return View("404");
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "Name", media.GenreId);
            return View("Edit",media);
        }

        // POST: Medias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MediaId,Title,MediaType,Season,Episode,ReleaseDate,GenreId")] Media media, IFormFile Poster, string CurrentPoster)
        {
            if (id != media.MediaId)
            {
                return View("404");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if(Poster != null)
                    {
                        var fileName = UploadPoster(Poster);
                        media.Poster = fileName;
                    }
                    else
                    {
                        //keep existing poster if no new photo is uploaded
                        media.Poster = CurrentPoster;
                    }
                    _context.Update(media);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MediaExists(media.MediaId))
                    {
                        return View("404");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "Name", media.GenreId);
            return View(media);
        }

        // GET: Medias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("404");
            }

            var media = await _context.Medias
                .Include(m => m.Genre)
                .FirstOrDefaultAsync(m => m.MediaId == id);
            if (media == null)
            {
                return View("404");
            }

            return View("Delete", media);
        }

        // POST: Medias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var media = await _context.Medias.FindAsync(id);
            _context.Medias.Remove(media);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MediaExists(int id)
        {
            return _context.Medias.Any(e => e.MediaId == id);
        }
    }
}

COMP2084-Project-200465920/Views/Browse/BrowseByGenre.cshtml
@model IEnumerable<COMP2084_Project_200465920.Models.Media>

@{ ViewData["Title"] = "Browse for media";}

<h1>Browse for @ViewBag.Genre</h1>

<section class="row card-group">
    @foreach (var m in Model)
    {
        <div class="clo-sm-6 col-lg-4 mb-3">
            <div class="card mb-3 text-center h-100">
                <div class="card-body">
                    <h5>
                        <a asp-controller="Medias" asp-action="Details" asp-route-id="@m.MediaId">
                            @m.Title
                        </a>
                    </h5>
                    @if (m.MediaType == "TV")
                    {
                        <h6>Season: @m.Season Episode: @m.Episode</h6>
                    }
                    else
                    { <h6>Movie</h6>}

                    @if (m.Poster != null)
                    {
                        <img src="~/photos/posters/@m.Poster" alt="Media poster" class="thumb" />
                    }
                    else
                    {
                        <img src="https://dummyimage.com/320x480" alt="Media poster" class="thumb" />
                    }
                    <form method="post" action="/WatchLists/AddMedia">
                       <label for="Watched"> Watched: </label>
                       <input type="checkbox" class="check-box" id="Watched" name="Watched" value="true">
                       <input type="hidden" name="MediaId" value="@m.MediaId" /><br />
                       <button class="btn btn-primary">Add to Watchlist</button>
                    </form>
                </div>

            </div>
        </div>
    }
</section>

COMP2084-Project-200465920/Views/Browse/Index.cshtml
@model IEnumerable<COMP2084_Project_200465920.Models.Genre>


@{ 
    ViewData["Title"] = "Check new releases";
}
<h1>Available Media</h1>
<section class="row card-group">
    @foreach(var c in Model)
            {
                <div class="col-sm-6 col-lg-4 mb-3">
                    <div class="card mb-4 text-center h-100">
                        <div class="card-body">
                            <a asp-controller="Browse" asp-action="BrowseByGenre" asp-route-id="@c.GenreId">
                                @c.Name
                            </a>
                        </div>
                    </div>
                </div>
            }
</section>