COMP2084-Project-200465920/Controllers/UserMediaController.cs
using COMP2084_Project_200465920.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace COMP2084_Project_200465920.Controllers
{
    public class UserMediaController : Controller
    {
        //add DbContext to use the database
        private readonly ApplicationDbContext _context;

        public UserMediaController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            // use genres DbSet to fetch list of categories to display to shoppers
            var genres = _context.Genres.OrderBy(c => c.Name).ToList();
            return View(genres);
        }
    }
}

COMP2084-Project-200465920/Views/UserMedia/Index.cshtml
@model IEnumerable<COMP2084_Project_200465920.Models.Genre>


@{ 
    ViewData["Title"] = "Check new releases";
}
<h1>Available Media</h1>
<section class="row card-group">
    @foreach(var c in Model)
            {
                <div class="col-sm-6 col-lg-4 mb-3">
                    <div class="card mb-4 text-center h-100">
                        <div class="card-body">
                            <a asp-controller="UserMedia" asp-action="BrowseGenre" asp-route-categoryid="@c.GenreId">
                                @c.Name
                            </a>
                        </div>
                    </div>
                </div>
            }
</section>